version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase ...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPO=$(aws ecr describe-repositories --repository-names example --output text --query "repositories[0].repositoryUri")
      - IMAGE=$REPO:latest
  build:
    commands:
      - echo Build started on `date`
      # - mvn install
      - docker build -t $IMAGE .
      - docker push $IMAGE
  post_build:
    commands:
      # - echo Build completed on `date`
      - printf '[{"name":"example","imageUri":"%s"}]' $IMAGE > imagedefinitions.json
artifacts:
  files: imagedifinitions.json
    # - target/messageUtil-1.0.jar
